# Generated by Django 5.2.1 on 2025-06-11 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_transaccion_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccion',
            old_name='usuario',
            new_name='vendedor',
        ),
    ]
