# Generated by Django 5.2.1 on 2025-06-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_rename_usuario_transaccion_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
