# Generated by Django 5.2.1 on 2025-06-11 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_transaccion_porcentaje_descuento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaccion',
            old_name='vendedor',
            new_name='usuario',
        ),
    ]
