# Generated by Django 5.2.1 on 2025-06-13 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_item_producto_codigo_item_producto_nombre_and_more'),
        ('ventas', '0005_rename_vendedor_transaccion_usuario'),
    ]

    operations = [
    ]
