# Generated by Django 5.2.1 on 2025-06-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_merge_20250613_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='eliminado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
