# Generated by Django 5.1.2 on 2024-10-20 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalle_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.detalleventa')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='inv.venta')),
            ],
        ),
    ]
