version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: manumarket_backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
