services:
  db:
    image: postgres:13
    container_name: manumarket_db
    environment:
      POSTGRES_DB:       manumarket
      POSTGRES_USER:     manumarket_user
      POSTGRES_PASSWORD: manumarket_pass
    volumes:
      - manumarket-data:/var/lib/postgresql/data
      - ./db_init/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql

  inventory_api:
    build: .
    container_name: inventory_api
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: manumarket
      DATABASE_USER: manumarket_user
      DATABASE_PASSWORD: manumarket_pass
      DATABASE_PORT: "5432"
    depends_on:
      - db

  sales_api:
    build: .
    container_name: sales_api
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/code
    ports:
      - "8002:8002"
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: manumarket
      DATABASE_USER: manumarket_user
      DATABASE_PASSWORD: manumarket_pass
      DATABASE_PORT: "5432"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4321:4321"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

volumes:
  manumarket-data:
