# Generated by Django 4.2.21 on 2025-05-14 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad vendida')),
                ('sale_price', models.DecimalField(decimal_places=2, help_text='Precio por unidad en el momento de la venta', max_digits=10, verbose_name='Precio de venta')),
                ('sold_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de venta')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='inventory.item', verbose_name='Artículo vendido')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-sold_at'],
            },
        ),
    ]
